name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      enable_perf_metrics:
        description: "Set VITE_ENABLE_PERF_METRICS at build time"
        required: false
        default: "false"
        type: choice
        options: ["false", "true"]
      enable_monitoring:
        description: "Set VITE_ENABLE_MONITORING at build time"
        required: false
        default: "false"
        type: choice
        options: ["false", "true"]
      ref:
        description: "Git ref (branch/tag) to deploy"
        required: false
        default: "main"
        type: string

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BASE_PATH: /${{ github.event.repository.name }}/
      VITE_ENABLE_PERF_METRICS: ${{ inputs.enable_perf_metrics || 'false' }}
      VITE_ENABLE_MONITORING: ${{ inputs.enable_monitoring || 'false' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || 'main' }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

        - name: Setup Pages
          uses: actions/configure-pages@v5

      - name: Build (Vite) with repo base path and flags
        run: npm run build -- --base=${{ env.BASE_PATH }}

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
